### ISSUE TITLE
Reduce step to 0.5 in routine detail intensity stepper

### ISSUE THREAD

**Issue by reedes** [gym-routine-tracker/Gym-Routine-Tracker-Watch-App#10]
To ease the configuration of oddball step values, such as 8.5.

Run screen intensity stepper should remain stepping at specified step value.

**Comment by Ahmed0Shaban** [comment]
I made a PR and I think problem is Solved

https://github.com/gym-routine-tracker/Gym-Routine-Tracker-Watch-App/pull/12#issue-1502017424

**Comment by reedes** [comment]
Thanks! I'm currently working on the iOS port and will publish new WatchOS version to App Store, likely by the end of the year.

**Comment by Ahmed0Shaban** [comment]
That's great, hope you do well and you can write to me if you need support.

**Comment by reedes** [comment]
I opted for more elaborate settings interface for the intensity stepper. When it escapes review in a few days see what you think!
